repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files

- repo: https://github.com/charliermarsh/ruff-pre-commit
  # Ruff version.
  rev: 'v0.5.6'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix, --config, line-length=100]
      exclude: ^(migrations/|__init__.py)
    - id: ruff-format

#- repo: https://github.com/psf/black
#  rev: 23.12.1
#  hooks:
#    - id: black
#      args: [-l 100]
#      language_version: python3.11
#      exclude: ^(migrations/|__init__.py)
